name: Back merge fuji to staging
on:
  push:
    branches:
      - 'fuji'

jobs:
  back_merge:
    runs-on: ubuntu-latest
    name: Back merge fuji to staging
    steps:
      - uses: actions/checkout@master

      - name: Merge fuji -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: fuji
          target_branch: staging
          github_token: ${{ secrets.GITHUB_TOKEN }}
