version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - REPOSITORY_URI=194943407731.dkr.ecr.eu-west-1.amazonaws.com/joeapi
      - IMAGE_TAG=${IMAGE_TAG:-$(echo $CODEBUILD_WEBHOOK_TRIGGER | awk -F/ {'print $2'})}
      - aws eks update-kubeconfig --name $ENVIRONMENT-trader-joe-eks
      - |
        for d in $(kubectl get deploy -n $ENVIRONMENT -l app=joepai --no-headers -o custom-columns=_:metadata.name); do
          kubectl set image -n $ENVIRONMENT deployment/$d $d=$REPOSITORY_URI:$IMAGE_TAG
        done
    finally:
      - bin/discord.sh
